services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jayseregon-portfolio
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/src/app
      - /src/app/node_modules
    command: npm run dev
