import { TimelineItem } from "@/interfaces/About";

export const getTimelineData = (t: any): TimelineItem[] => [
  {
    date: t("item1.date"),
    label: t("item1.label"),
    city: t("item1.city"),
    company: t("item1.company"),
    keywords: [
      "Python",
      "React",
      "Next.js",
      "OpenAI",
      "Swift",
      "SwiftUI",
      "Vercel",
      "Resend",
      "Automation",
      "Postgres",
      "Prisma",
      "GitHub",
      "Copilot",
      "AI",
      "Web",
      "Full-stack",
    ],
    summary: t("item1.summary"),
    description: [
      t("item1.description.p1"),
      t("item1.description.p2"),
      t("item1.description.p3"),
      t("item1.description.p4"),
      t("item1.description.p5"),
    ],
    timelineIcon: "work",
    href: "",
  },
  {
    date: t("item2.date"),
    label: t("item2.label"),
    company: t("item2.company"),
    city: t("item2.city"),
    keywords: [
      "RNNs",
      "Computer Vision",
      "Convolutional Neural Network",
      "Forecasting",
      "Transfer Learning",
      "Python",
      "Tokenization",
      "Dropouts",
      "Natural Language Processing",
      "TensorFlow",
      "Augmentation",
    ],
    summary: t("item2.summary"),
    description: [],
    timelineIcon: "award",
    href: "https://coursera.org/share/044bfdd0bccbc91b4c673f8feec27713",
  },
  {
    date: t("item3.date"),
    label: t("item3.label"),
    company: t("item3.company"),
    city: t("item3.city"),
    keywords: [
      "Recurrent Neural Network",
      "Tensorflow",
      "Computer Vision",
      "Network Architecture",
      "Python",
      "Convolutional Neural Network",
      "Artificial Neural Network",
      "Transformers",
    ],
    summary: t("item3.summary"),
    description: [],
    timelineIcon: "award",
    href: "https://coursera.org/share/a93febee65e0ce9ede416e0706c60271",
  },
  {
    date: t("item4.date"),
    label: t("item4.label"),
    company: t("item4.company"),
    city: t("item4.city"),
    keywords: [
      "Machine Learning",
      "Machine Learning Algorithms",
      "Applied Machine Learning",
      "Algorithms",
      "Deep Learning",
      "Artificial Neural Networks",
      "Human Learning",
      "Python",
      "Regression",
      "Critical Thinking",
      "Network Model",
    ],
    summary: t("item4.summary"),
    description: [],
    timelineIcon: "award",
    href: "https://coursera.org/share/7a613f9b7798a93c8f60fb750320fa56",
  },
  {
    date: t("item5.date"),
    label: t("item5.label"),
    company: t("item5.company"),
    city: t("item5.city"),
    keywords: [
      "Python",
      "Django",
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind",
      "API",
      "OpenAI",
      "AI",
      "Langchain",
      "Postgres",
      "Prisma",
      "Docker",
      "Azure",
      "GitHub",
      "Copilot",
      "CI/CD",
      "Cloud",
      "GIS",
      "Leadership",
      "Automation",
    ],
    summary: t("item5.summary"),
    description: [
      t("item5.description.p1"),
      t("item5.description.p2"),
      t("item5.description.p3"),
      t("item5.description.p4"),
      t("item5.description.p5"),
      t("item5.description.p6"),
      t("item5.description.p7"),
    ],
    timelineIcon: "work",
    href: "",
  },
  {
    date: t("item6.date"),
    label: t("item6.label"),
    city: t("item6.city"),
    company: t("item6.company"),
    keywords: [
      "Python",
      "React",
      "Next.js",
      "GitHub",
      "Swift",
      "SwiftUI",
      "Vercel",
      "Resend",
      "Stripe",
      "E-commerce",
      "Full-stack Development",
      "Business Strategy",
      "Web Architecture",
    ],
    summary: t("item6.summary"),
    description: [
      t("item6.description.p1"),
      t("item6.description.p2"),
      t("item6.description.p3"),
      t("item6.description.p4"),
    ],
    timelineIcon: "work",
    href: "",
  },
  {
    date: t("item7.date"),
    label: t("item7.label"),
    company: t("item7.company"),
    city: t("item7.city"),
    keywords: [
      "Python",
      "Django",
      "Bootstrap",
      "Automation",
      "Docker",
      "Azure",
      "GitHub",
      "GIS",
      "PostGIS",
      "Postgres",
      "AutoCAD",
      "Network Design",
      "Process Optimization",
      "Data Analysis",
    ],
    summary: t("item7.summary"),
    description: [
      t("item7.description.p1"),
      t("item7.description.p2"),
      t("item7.description.p3"),
      t("item7.description.p4"),
      t("item7.description.p5"),
      t("item7.description.p6"),
      t("item7.description.p7"),
    ],
    timelineIcon: "work",
    href: "",
  },
  {
    date: t("item8.date"),
    label: t("item8.label"),
    city: t("item8.city"),
    company: t("item8.company"),
    keywords: [
      "Python",
      "Postgres",
      "PostGIS",
      "ArcGIS",
      "QGIS",
      "Illustrator",
    ],
    summary: t("item8.summary"),
    description: [],
    timelineIcon: "school",
    href: "",
  },
  {
    date: t("item9.date"),
    label: t("item9.label"),
    city: t("item9.city"),
    company: t("item9.company"),
    keywords: ["Postgres", "ArcGIS", "QGIS", "Illustrator"],
    summary: t("item9.summary"),
    description: [],
    timelineIcon: "school",
    href: "",
  },
];
