export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Jerenyon",
  siteUrl: "https://www.jerenyon.dev",
  heroTitle: "Building the Future with AI & Automation",
  heroSubtitle:
    "Bridging Generative AI, Automation, and Geospatial Intelligence for Smarter, Scalable Solutions.",
  heroDescription:
    "Delivering cutting-edge AI-powered automation, web development, and geospatial intelligence solutions. Specialized in Generative AI, cloud-based GIS, Python automation, and AI-driven innovation tailored to your needs.",
  keywords: [
    "Generative AI",
    "AI Automation",
    "AI Solutions",
    "Large Language Models",
    "LLMs",
    "Retrieval-Augmented Generation",
    "RAG Systems",
    "AI Agents",
    "Vector Databases",
    "LangChain",
    "CrewAI",
    "Hugging Face",
    "Machine Learning",
    "Artificial Intelligence",
    "Python",
    "Python Automation",
    "Web Development",
    "Cloud Applications",
    "Next.js",
    "TypeScript",
    "Full Stack Development",
    "Django",
    "FastAPI",
    "Geospatial Intelligence",
    "GIS",
    "Geospatial Data Processing",
    "Interactive Mapping Tools",
    "Geospatial Workflows",
    "Custom AI Solutions",
    "AI-Augmented Development",
    "Workflow Automation",
    "Cloud Infrastructure",
    "PostGIS",
    "MongoDB",
    "ChromaDB",
    "Neo4j",
  ],
  icon: "/favicon.webp",
  navItems: [
    {
      label: "about",
      href: "/about",
    },
    {
      label: "knowledge-hub",
      href: "/knowledge-hub",
    },
    {
      label: "estimate",
      href: "/estimate",
    },
    {
      label: "contact",
      href: "/contact",
    },
  ],
  knowledgeHub: [
    {
      label: "articles",
      rootRef: "/knowledge-hub",
    },
  ],
  links: {},
};
